# Generated by Django 4.0 on 2022-02-08 20:12

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='convention',
            fields=[
                ('id_convention', models.CharField(max_length=12, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='encadreur',
            fields=[
                ('id_encadreur', models.CharField(max_length=12, primary_key=True, serialize=False)),
                ('nom_encad', models.CharField(max_length=30)),
                ('prenom_encad', models.CharField(max_length=30)),
                ('email_encad', models.EmailField(blank=True, max_length=254)),
                ('numtel_encad', models.IntegerField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='entreprise',
            fields=[
                ('id_entreprise', models.CharField(max_length=12, primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=30)),
                ('numero', models.IntegerField(null=True)),
                ('mail', models.EmailField(max_length=254, null=True)),
                ('adresseEnt', models.CharField(blank=True, max_length=30, null=True)),
                ('TypeEnt', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='promoteur',
            fields=[
                ('id_promoteur', models.CharField(max_length=12, primary_key=True, serialize=False)),
                ('nom_prom', models.CharField(max_length=30)),
                ('prenom_prom', models.CharField(max_length=30)),
                ('email_prom', models.EmailField(blank=True, max_length=254)),
                ('numtel_prom', models.IntegerField(blank=True)),
                ('nom_entreprise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.entreprise')),
            ],
        ),
        migrations.CreateModel(
            name='soutenance',
            fields=[
                ('id_soutenance', models.CharField(max_length=12, primary_key=True, serialize=False)),
                ('date_soutenance', models.DateField()),
                ('jury', models.ManyToManyField(to='app.encadreur')),
            ],
        ),
        migrations.CreateModel(
            name='stagiaire',
            fields=[
                ('matricule', models.IntegerField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=30)),
                ('prenom', models.CharField(max_length=30)),
                ('date_naissance', models.DateField()),
                ('annee', models.CharField(choices=[('1cp', '1 er cycle preparatoire'), ('2cp', '2eme cycle preparatoire'), ('1cs', '1 er cycle superieur'), ('2cs', '2 eme cycle superieur'), ('3cs', '3 eme cycle superieur')], default='1cp', max_length=3)),
                ('specialite', models.CharField(choices=[('SIT', "systeme d'information"), ('SIL', "Systeme d'informations et logiciels "), ('SIQ', 'systeme informatique'), ('SID', 'Intelligence artifficielle')], default='section 1', max_length=5)),
                ('section', models.CharField(default='section 1', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='stage',
            fields=[
                ('code', models.CharField(max_length=12, primary_key=True, serialize=False)),
                ('titre', models.CharField(max_length=50)),
                ('type', models.CharField(choices=[('OUVRIER', 'Stage OUVRIER'), ('PFE', 'Stage PFE'), ('TECH', 'Stage TECHNIQUE')], default='PFE', max_length=50)),
                ('description', models.CharField(default='', max_length=100)),
                ('annee', models.CharField(blank=True, max_length=10, null=True)),
                ('mention', models.CharField(choices=[('Bien', 'Bien'), ('TBien', 'Tres Bien'), ('Excellent', 'Excellent')], default='None', max_length=50)),
                ('Convention', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.convention')),
                ('Id_soutenance', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.soutenance')),
                ('encadreurs', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.encadreur')),
                ('entreprise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.entreprise')),
                ('promoteurs', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.promoteur')),
                ('stagiaires', models.ManyToManyField(null=True, to='app.stagiaire')),
            ],
        ),
        migrations.CreateModel(
            name='rapport',
            fields=[
                ('id_rapport', models.CharField(max_length=12, primary_key=True, serialize=False)),
                ('titre', models.CharField(max_length=50)),
                ('nbrpages', models.IntegerField(validators=[django.core.validators.MaxValueValidator(120), django.core.validators.MinValueValidator(6)])),
                ('file', models.FileField(upload_to='media/rapports')),
                ('stage', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.stage')),
            ],
        ),
        migrations.CreateModel(
            name='ficheSuivi',
            fields=[
                ('id_ficheSuivi', models.CharField(max_length=12, primary_key=True, serialize=False)),
                ('date_depot', models.DateField()),
                ('Encadreur', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.encadreur')),
            ],
        ),
        migrations.CreateModel(
            name='ficheEvaluation',
            fields=[
                ('id_ficheEvaluation', models.CharField(max_length=12, primary_key=True, serialize=False)),
                ('remarques', models.CharField(max_length=100)),
                ('Stage', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app.stage')),
            ],
        ),
        migrations.AddField(
            model_name='convention',
            name='numStage',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.stage'),
        ),
    ]
